### ISSUE TITLE
Probleme beim Kompilieren

### ISSUE THREAD

**Issue by SBajonczak** [hiveeyes/hiveeyes-epaper-display#3]
Wenn man das Projekt direkt Kompilieren will erhält man schnell den folgenden Fehler 

`Compiling .pio\build\esp32\lib596\GxEPD2\epd3c\GxEPD2_583c.cpp.o
In file included from .pio\libdeps\esp32\Adafruit GFX Library\Adafruit_GrayOLED.cpp:20:0:
.pio\libdeps\esp32\Adafruit GFX Library\Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory`

Hier fehlt noch die Referenz auf 

`#include <Adafruit_I2CDevice.h>`

**Comment by amotl** [comment]
Vielen Dank!
